//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace AS.HDFql {

		using System;
	
class HDFqlPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="SWIGRegisterExceptionCallbacks_HDFql")]
    public static extern void SWIGRegisterExceptionCallbacks_HDFql(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_HDFql")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_HDFql(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_HDFql(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_HDFql(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(HDFqlPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(HDFqlPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="SWIGRegisterStringCallback_HDFql")]
    public static extern void SWIGRegisterStringCallback_HDFql(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_HDFql(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static HDFqlPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_delete_HDFqlCursor___")]
  public static extern void delete_HDFqlCursor(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_new_HDFqlCursor___")]
  public static extern global::System.IntPtr new_HDFqlCursor();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Version_get___")]
  public static extern string Version_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Yes_get___")]
  public static extern int Yes_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_No_get___")]
  public static extern int No_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Enabled_get___")]
  public static extern int Enabled_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Disabled_get___")]
  public static extern int Disabled_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Unlimited_get___")]
  public static extern int Unlimited_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Undefined_get___")]
  public static extern int Undefined_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Directory_get___")]
  public static extern int Directory_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_File_get___")]
  public static extern int File_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Group_get___")]
  public static extern int Group_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Dataset_get___")]
  public static extern int Dataset_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Attribute_get___")]
  public static extern int Attribute_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_SoftLink_get___")]
  public static extern int SoftLink_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ExternalLink_get___")]
  public static extern int ExternalLink_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Tinyint_get___")]
  public static extern int Tinyint_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_UnsignedTinyint_get___")]
  public static extern int UnsignedTinyint_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Smallint_get___")]
  public static extern int Smallint_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_UnsignedSmallint_get___")]
  public static extern int UnsignedSmallint_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Int_get___")]
  public static extern int Int_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_UnsignedInt_get___")]
  public static extern int UnsignedInt_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Bigint_get___")]
  public static extern int Bigint_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_UnsignedBigint_get___")]
  public static extern int UnsignedBigint_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Float_get___")]
  public static extern int Float_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Double_get___")]
  public static extern int Double_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Char_get___")]
  public static extern int Char_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Vartinyint_get___")]
  public static extern int Vartinyint_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_UnsignedVartinyint_get___")]
  public static extern int UnsignedVartinyint_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Varsmallint_get___")]
  public static extern int Varsmallint_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_UnsignedVarsmallint_get___")]
  public static extern int UnsignedVarsmallint_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Varint_get___")]
  public static extern int Varint_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_UnsignedVarint_get___")]
  public static extern int UnsignedVarint_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Varbigint_get___")]
  public static extern int Varbigint_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_UnsignedVarbigint_get___")]
  public static extern int UnsignedVarbigint_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Varfloat_get___")]
  public static extern int Varfloat_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Vardouble_get___")]
  public static extern int Vardouble_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Varchar_get___")]
  public static extern int Varchar_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Opaque_get___")]
  public static extern int Opaque_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Bitfield_get___")]
  public static extern int Bitfield_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Enumeration_get___")]
  public static extern int Enumeration_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Compound_get___")]
  public static extern int Compound_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Reference_get___")]
  public static extern int Reference_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Global_get___")]
  public static extern int Global_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Local_get___")]
  public static extern int Local_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Tracked_get___")]
  public static extern int Tracked_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Indexed_get___")]
  public static extern int Indexed_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Contiguous_get___")]
  public static extern int Contiguous_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Compact_get___")]
  public static extern int Compact_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Chunked_get___")]
  public static extern int Chunked_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Early_get___")]
  public static extern int Early_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Incremental_get___")]
  public static extern int Incremental_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Late_get___")]
  public static extern int Late_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_LittleEndian_get___")]
  public static extern int LittleEndian_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_BigEndian_get___")]
  public static extern int BigEndian_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_MixedEndian_get___")]
  public static extern int MixedEndian_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Ascii_get___")]
  public static extern int Ascii_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Utf8_get___")]
  public static extern int Utf8_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_FillDefault_get___")]
  public static extern int FillDefault_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_FillDefined_get___")]
  public static extern int FillDefined_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_FillNever_get___")]
  public static extern int FillNever_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_FillUndefined_get___")]
  public static extern int FillUndefined_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Earliest_get___")]
  public static extern int Earliest_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Latest_get___")]
  public static extern int Latest_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Version18_get___")]
  public static extern int Version18_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Success_get___")]
  public static extern int Success_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorParse_get___")]
  public static extern int ErrorParse_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorNotSpecified_get___")]
  public static extern int ErrorNotSpecified_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorNotFound_get___")]
  public static extern int ErrorNotFound_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorNoAccess_get___")]
  public static extern int ErrorNoAccess_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorNotOpen_get___")]
  public static extern int ErrorNotOpen_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorInvalidName_get___")]
  public static extern int ErrorInvalidName_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorInvalidFile_get___")]
  public static extern int ErrorInvalidFile_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorNotSupported_get___")]
  public static extern int ErrorNotSupported_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorNotEnoughSpace_get___")]
  public static extern int ErrorNotEnoughSpace_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorNotEnoughMemory_get___")]
  public static extern int ErrorNotEnoughMemory_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorAlreadyExists_get___")]
  public static extern int ErrorAlreadyExists_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorEmpty_get___")]
  public static extern int ErrorEmpty_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorFull_get___")]
  public static extern int ErrorFull_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorBeforeFirst_get___")]
  public static extern int ErrorBeforeFirst_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorAfterLast_get___")]
  public static extern int ErrorAfterLast_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorOutsideLimit_get___")]
  public static extern int ErrorOutsideLimit_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorNoAddress_get___")]
  public static extern int ErrorNoAddress_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorUnexpectedType_get___")]
  public static extern int ErrorUnexpectedType_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorUnexpectedDataType_get___")]
  public static extern int ErrorUnexpectedDataType_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorUnexpectedStorageType_get___")]
  public static extern int ErrorUnexpectedStorageType_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorDanglingLink_get___")]
  public static extern int ErrorDanglingLink_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorNotRegistered_get___")]
  public static extern int ErrorNotRegistered_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorInvalidRegularExpression_get___")]
  public static extern int ErrorInvalidRegularExpression_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorInvalidSelection_get___")]
  public static extern int ErrorInvalidSelection_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorUnknown_get___")]
  public static extern int ErrorUnknown_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CSharp_get___")]
  public static extern int CSharp_get();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ExecuteGetStatus___")]
  public static extern int ExecuteGetStatus();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorGetLine___")]
  public static extern int ErrorGetLine();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorGetPosition___")]
  public static extern int ErrorGetPosition();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ErrorGetMessage___")]
  public static extern string ErrorGetMessage();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_MpiGetSize___")]
  public static extern int MpiGetSize();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_MpiGetRank___")]
  public static extern int MpiGetRank();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_Execute___")]
  public static extern int Execute(string jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_ExecuteReset___")]
  public static extern int ExecuteReset();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_VariableRegister___")]
  public static extern void VariableRegister(int jarg1, int jarg2, IntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_VariableUnregister___")]
  public static extern void VariableUnregister(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_VariableGetDataType___")]
  public static extern int VariableGetDataType(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_VariableGetCount___")]
  public static extern int VariableGetCount(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_VariableGetSize___")]
  public static extern int VariableGetSize(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_VariableGetDimensionCount___")]
  public static extern int VariableGetDimensionCount(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_VariableGetDimension___")]
  public static extern long VariableGetDimension(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorInitialize___")]
  public static extern int CursorInitialize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorUse___")]
  public static extern int CursorUse(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorUseDefault___")]
  public static extern int CursorUseDefault();

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorClear___")]
  public static extern int CursorClear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorClone___")]
  public static extern int CursorClone(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorGetDataType___")]
  public static extern int CursorGetDataType(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorGetCount___")]
  public static extern int CursorGetCount(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_SubcursorGetCount___")]
  public static extern int SubcursorGetCount(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorGetPosition___")]
  public static extern int CursorGetPosition(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_SubcursorGetPosition___")]
  public static extern int SubcursorGetPosition(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorFirst___")]
  public static extern int CursorFirst(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_SubcursorFirst___")]
  public static extern int SubcursorFirst(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorLast___")]
  public static extern int CursorLast(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_SubcursorLast___")]
  public static extern int SubcursorLast(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorNext___")]
  public static extern int CursorNext(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_SubcursorNext___")]
  public static extern int SubcursorNext(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorPrevious___")]
  public static extern int CursorPrevious(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_SubcursorPrevious___")]
  public static extern int SubcursorPrevious(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorAbsolute___")]
  public static extern int CursorAbsolute(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_SubcursorAbsolute___")]
  public static extern int SubcursorAbsolute(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorRelative___")]
  public static extern int CursorRelative(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_SubcursorRelative___")]
  public static extern int SubcursorRelative(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorGetTinyint___")]
  public static extern IntPtr CursorGetTinyint(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_SubcursorGetTinyint___")]
  public static extern IntPtr SubcursorGetTinyint(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorGetUnsignedTinyint___")]
  public static extern global::System.IntPtr CursorGetUnsignedTinyint(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_SubcursorGetUnsignedTinyint___")]
  public static extern global::System.IntPtr SubcursorGetUnsignedTinyint(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorGetSmallint___")]
  public static extern global::System.IntPtr CursorGetSmallint(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_SubcursorGetSmallint___")]
  public static extern global::System.IntPtr SubcursorGetSmallint(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorGetUnsignedSmallint___")]
  public static extern global::System.IntPtr CursorGetUnsignedSmallint(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_SubcursorGetUnsignedSmallint___")]
  public static extern global::System.IntPtr SubcursorGetUnsignedSmallint(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorGetInt___")]
  public static extern global::System.IntPtr CursorGetInt(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_SubcursorGetInt___")]
  public static extern global::System.IntPtr SubcursorGetInt(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorGetUnsignedInt___")]
  public static extern global::System.IntPtr CursorGetUnsignedInt(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_SubcursorGetUnsignedInt___")]
  public static extern global::System.IntPtr SubcursorGetUnsignedInt(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorGetBigint___")]
  public static extern global::System.IntPtr CursorGetBigint(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_SubcursorGetBigint___")]
  public static extern global::System.IntPtr SubcursorGetBigint(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorGetUnsignedBigint___")]
  public static extern global::System.IntPtr CursorGetUnsignedBigint(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_SubcursorGetUnsignedBigint___")]
  public static extern global::System.IntPtr SubcursorGetUnsignedBigint(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorGetFloat___")]
  public static extern global::System.IntPtr CursorGetFloat(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_SubcursorGetFloat___")]
  public static extern global::System.IntPtr SubcursorGetFloat(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorGetDouble___")]
  public static extern global::System.IntPtr CursorGetDouble(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_SubcursorGetDouble___")]
  public static extern global::System.IntPtr SubcursorGetDouble(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HDFql", EntryPoint="CSharp_ASfHDFql_CursorGetChar___")]
  public static extern string CursorGetChar(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}
