# Copyright (C) 2021 Thomas Friedrich, Chu-Ping Yu,
# University of Antwerp - All Rights Reserved.
# You may use, distribute and modify
# this code under the terms of the GPL3 license.
# You should have received a copy of the GPL3 license with
# this file. If not, please visit:
# https://www.gnu.org/licenses/gpl-3.0.en.html

# Authors:
#   Thomas Friedrich <thomas.friedrich@uantwerpen.be>
#   Chu-Ping Yu <chu-ping.yu@uantwerpen.be>

name: BUILD

on: [push, pull_request, workflow_dispatch]

jobs:
  build_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86

      - name: get sdl, fftw
        run: |
          curl.exe http://www.libsdl.org/release/SDL2-devel-2.0.16-VC.zip --output sdl.zip
          curl.exe http://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip --output sdl_im.zip
          tar -xf sdl.zip
          tar -xf sdl_im.zip
          ren SDL2_image-2.0.5 SDL2_IM_VC
          ren SDL2-2.0.16 SDL2_VC
          move .\SDL2_IM_VC\include\* .\SDL2_VC\include\
          move .\SDL2_IM_VC\lib\x64\* .\SDL2_VC\lib\x64
          move .\SDL2_IM_VC\lib\x86\* .\SDL2_VC\lib\x86
          move SDL2_VC C:\
          del sdl.zip
          del sdl_im.zip
          mkdir FFTW
          cd FFTW
          curl.exe https://fftw.org/pub/fftw/fftw-3.3.5-dll64.zip --output fftw.zip
          tar -xf fftw.zip
          del fftw.zip
          lib /machine:x64 /def:libfftw3f-3.def
          cd ..
          move FFTW C:\

      - name: Build with MSVC
        run: |
          mkdir build
          cd build
          cmake ..
          msbuild .\RICOM.vcxproj /p:configuration=Release
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Release_Win
          path: |
            build\Release

  build_Linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Get SDL2, fftw3 and gcc-9
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev libsdl2-image-dev libfftw3-dev gcc-9 g++-9
      - name: Build
        env:
          CC: gcc-9
          CXX: g++-9
        run: |
          cmake . -D CMAKE_BUILD_TYPE=Release
          make
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Release_Linux
          path: |
            RICOM
